### PR TITLE
Throw CloudflareError instead of JSON error

### PR DESCRIPTION
**Pull request by sarxos**
Hi @LoadLow,

While using Cloudflare API I was hit by the problem described in https://github.com/sarxos/cloudflare-api/issues/1. This pull request is to cherry pick this change onto your code base.

The previous stack trace:

``` plain
Exception in thread "pool-1-thread-16" net.sf.json.JSONException: JSONObject["err_code"] not found.
    at net.sf.json.JSONObject.getString(JSONObject.java:2092)
    at com.cloudflare.api.requests.CloudflareRequest.executeBasic(CloudflareRequest.java:90)
    at com.cloudflare.api.requests.purge.PurgeCacheFile.execute(PurgeCacheFile.java:21)
    at x.x.x.CloudflareService.purge(CloudflareService.java:42)
    at A$1.run(A.java:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

After the change:

``` plain
com.cloudflare.api.results.CloudflareError: [UNKNOWN_ERROR] : Cannot execute request :: Purge rate limited.
    at com.cloudflare.api.results.CloudflareErrorEnum$1.getException(CloudflareErrorEnum.java:13) ~[classes/:na]
    at com.cloudflare.api.requests.CloudflareRequest.executeBasic(CloudflareRequest.java:105) ~[classes/:na]
    at com.cloudflare.api.requests.purge.PurgeCacheFile.execute(PurgeCacheFile.java:21) ~[classes/:na]
    at x.x.x.CloudflareService.purge(CloudflareService.java:42) ~[classes/:na]
    at A$1.run(A.java:21) [classes/:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

The code I used to test it:

``` java
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import x.x.x.CloudflareService;


public class A {

    public static void main(String[] args) {

        ExecutorService executor = Executors.newFixedThreadPool(20);

        final CloudflareService cdn = new CloudflareService();

        for (int i = 0; i < 101; i++) {
            final int k = i;
            executor.execute(new Runnable() {

                @Override
                public void run() {
                    cdn.purge(k + "test.js");
                }
            });
        }
    }
}
```

### CODE REVIEW

**Comment by LoadLow** [comment]
Thanks to report.
To improve performances, i think we need to use UrlConnections instead of Apache HTTP Client...

**Comment by sarxos** [comment]
Hi @LoadLow, 

I have to admit that Apache HttpClient saved my life here because I was easily able to turn on wire log on the site and take a look what has been sent to the Cloudflare API and what caused this particular error. Otherwise I would have to connect debugger to my EC2 instance which is not so easy in the AWS.

Moreover, I had to decrease performance because I hit the Cloudflare limitations (max 100 requests per minute to purge cache and max 1200 requests per 5 minutes) :( I had to add `Thread.sleep(600)` in my code because it was sending requests too fast.

I would suggest to leave the Apache HttpClient for few reasons:
- Good logging support,
- Various proxies support,
- HttpComponents users community willing to help with the issues.

The above may be hard to implement when you decide to move to `URLConnection`.

**Comment by LoadLow** [comment]
Hi,
okay no problem :).
You could use ScheduledExecutors too, or enable "Development mode" on Cloudflare instead of always purge these files when you're testing your files.

**Comment by sarxos** [comment]
Thanks for hints @LoadLow :) Your Cloudflare API is very useful piece of code. Thank you for making it!

Take care!

**Comment by LoadLow** [comment]
Thank you :D !

**Pull request merged**
